/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotalRouteImport } from './routes/total'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PercentagesIndexRouteImport } from './routes/percentages/index'
import { Route as JobInformationIndexRouteImport } from './routes/job-information/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as PercentagesAddRulesRouteImport } from './routes/percentages/addRules'
import { Route as JobInformationAddJobRouteImport } from './routes/job-information/addJob'
import { Route as ExpensesAddExpensesRouteImport } from './routes/expenses/addExpenses'

const VerifyLazyRouteImport = createFileRoute('/verify')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgotPassword')()
const Change_passwordLazyRouteImport = createFileRoute('/change_password')()

const VerifyLazyRoute = VerifyLazyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/verify.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgotPassword.lazy').then((d) => d.Route),
)
const Change_passwordLazyRoute = Change_passwordLazyRouteImport.update({
  id: '/change_password',
  path: '/change_password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/change_password.lazy').then((d) => d.Route),
)
const TotalRoute = TotalRouteImport.update({
  id: '/total',
  path: '/total',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentagesIndexRoute = PercentagesIndexRouteImport.update({
  id: '/percentages/',
  path: '/percentages/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobInformationIndexRoute = JobInformationIndexRouteImport.update({
  id: '/job-information/',
  path: '/job-information/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentagesAddRulesRoute = PercentagesAddRulesRouteImport.update({
  id: '/percentages/addRules',
  path: '/percentages/addRules',
  getParentRoute: () => rootRouteImport,
} as any)
const JobInformationAddJobRoute = JobInformationAddJobRouteImport.update({
  id: '/job-information/addJob',
  path: '/job-information/addJob',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesAddExpensesRoute = ExpensesAddExpensesRouteImport.update({
  id: '/expenses/addExpenses',
  path: '/expenses/addExpenses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/total': typeof TotalRoute
  '/change_password': typeof Change_passwordLazyRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/verify': typeof VerifyLazyRoute
  '/expenses/addExpenses': typeof ExpensesAddExpensesRoute
  '/job-information/addJob': typeof JobInformationAddJobRoute
  '/percentages/addRules': typeof PercentagesAddRulesRoute
  '/expenses': typeof ExpensesIndexRoute
  '/job-information': typeof JobInformationIndexRoute
  '/percentages': typeof PercentagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/total': typeof TotalRoute
  '/change_password': typeof Change_passwordLazyRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/verify': typeof VerifyLazyRoute
  '/expenses/addExpenses': typeof ExpensesAddExpensesRoute
  '/job-information/addJob': typeof JobInformationAddJobRoute
  '/percentages/addRules': typeof PercentagesAddRulesRoute
  '/expenses': typeof ExpensesIndexRoute
  '/job-information': typeof JobInformationIndexRoute
  '/percentages': typeof PercentagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/total': typeof TotalRoute
  '/change_password': typeof Change_passwordLazyRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/verify': typeof VerifyLazyRoute
  '/expenses/addExpenses': typeof ExpensesAddExpensesRoute
  '/job-information/addJob': typeof JobInformationAddJobRoute
  '/percentages/addRules': typeof PercentagesAddRulesRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/job-information/': typeof JobInformationIndexRoute
  '/percentages/': typeof PercentagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/total'
    | '/change_password'
    | '/forgotPassword'
    | '/verify'
    | '/expenses/addExpenses'
    | '/job-information/addJob'
    | '/percentages/addRules'
    | '/expenses'
    | '/job-information'
    | '/percentages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/total'
    | '/change_password'
    | '/forgotPassword'
    | '/verify'
    | '/expenses/addExpenses'
    | '/job-information/addJob'
    | '/percentages/addRules'
    | '/expenses'
    | '/job-information'
    | '/percentages'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/total'
    | '/change_password'
    | '/forgotPassword'
    | '/verify'
    | '/expenses/addExpenses'
    | '/job-information/addJob'
    | '/percentages/addRules'
    | '/expenses/'
    | '/job-information/'
    | '/percentages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TotalRoute: typeof TotalRoute
  Change_passwordLazyRoute: typeof Change_passwordLazyRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  VerifyLazyRoute: typeof VerifyLazyRoute
  ExpensesAddExpensesRoute: typeof ExpensesAddExpensesRoute
  JobInformationAddJobRoute: typeof JobInformationAddJobRoute
  PercentagesAddRulesRoute: typeof PercentagesAddRulesRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  JobInformationIndexRoute: typeof JobInformationIndexRoute
  PercentagesIndexRoute: typeof PercentagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change_password': {
      id: '/change_password'
      path: '/change_password'
      fullPath: '/change_password'
      preLoaderRoute: typeof Change_passwordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/total': {
      id: '/total'
      path: '/total'
      fullPath: '/total'
      preLoaderRoute: typeof TotalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentages/': {
      id: '/percentages/'
      path: '/percentages'
      fullPath: '/percentages'
      preLoaderRoute: typeof PercentagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-information/': {
      id: '/job-information/'
      path: '/job-information'
      fullPath: '/job-information'
      preLoaderRoute: typeof JobInformationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentages/addRules': {
      id: '/percentages/addRules'
      path: '/percentages/addRules'
      fullPath: '/percentages/addRules'
      preLoaderRoute: typeof PercentagesAddRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-information/addJob': {
      id: '/job-information/addJob'
      path: '/job-information/addJob'
      fullPath: '/job-information/addJob'
      preLoaderRoute: typeof JobInformationAddJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/addExpenses': {
      id: '/expenses/addExpenses'
      path: '/expenses/addExpenses'
      fullPath: '/expenses/addExpenses'
      preLoaderRoute: typeof ExpensesAddExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TotalRoute: TotalRoute,
  Change_passwordLazyRoute: Change_passwordLazyRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  VerifyLazyRoute: VerifyLazyRoute,
  ExpensesAddExpensesRoute: ExpensesAddExpensesRoute,
  JobInformationAddJobRoute: JobInformationAddJobRoute,
  PercentagesAddRulesRoute: PercentagesAddRulesRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  JobInformationIndexRoute: JobInformationIndexRoute,
  PercentagesIndexRoute: PercentagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
